config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index] do
    resources :secrets, :only => :new
    resources :friendships, :only => :create
  end
  resources :secrets, :only => :create
  resource :session, :only => [:create, :destroy, :new]
  resources :friendships, :only => :destroy

  root :to => "users#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  validates :out_friend, :in_friend, :presence => true

  belongs_to :out_friend, :class_name => "User"
  belongs_to :in_friend, :class_name => "User"

  def self.can_friend?(out_friend_id, in_friend_id)
    !(Friendship.exists?(
      :out_friend_id => out_friend_id,
      :in_friend_id => in_friend_id
    ) || out_friend_id == in_friend_id)
  end

  def self.can_unfriend?(out_friend_id, in_friend_id)
    Friendship.exists?(
      :out_friend_id => out_friend_id,
      :in_friend_id => in_friend_id
    )
  end

  def self.getFriendship(out_id, in_id)
    Friendship.find_by_out_friend_id_and_in_friend_id(out_id, in_id)
  end
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :title

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
  has_many :secret_taggings
  has_many :tags, :through => :secret_taggings, :source => :tag

  validates :author_id, :recipient_id, :title, :presence => true
end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :secret_id, :tag_id

  validates :secret, :tag, :presence => true

  belongs_to :secret
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true, :uniqueness => true

  has_many :secret_taggings
  has_many :secrets, :through => :secret_taggings, :source => :secret
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  has_many :friendships, :foreign_key => :out_friend_id
  has_many :friends, :through => :friendships, :source => :in_friend

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = Friendship.new()
    @friendship.out_friend = current_user
    @friendship.in_friend_id = params[:user_id]
    @friendship.save!
    render :json => @friendship
  end

  def destroy
    friendship = Friendship.find(params[:id])
    friendship.destroy
    head :ok
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
    render :new
  end

  def create
    @secret = Secret.new(params[:secret])
    @secret.author = current_user

    if @secret.save
      render :json => @secret
    else
      flash.now[:errors] = @secret.errors.full_messages
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def index
    @users = User.all
    @friendships = current_user.friendships
    render :index
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash[:errors] && flash[:errors].each do |error| %>
	<%= error %>
<% end%>

<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<form class="secret">

	<input type="hidden" name="authenticity_token"
	 value="<%= form_authenticity_token %>">

	 <input type="hidden" name="secret[recipient_id]"
	 value="<%= params[:id] %>">

	<label for="secret">Secret</label>
	<input type="text" name="secret[title]" id="secret">
	<br>
	<a href="#" id="secret_submit">Add Tag</a>

	<input type="submit">
</form>

app/views/secrets/new.html.erb
<form action="<%= secrets_url %>" method="POST">

	<input type="hidden" name="authenticity_token"
	 value="<%= form_authenticity_token %>">

	 <input type="hidden" name="secret[recipient_id]"
	 value="<%= params[:user_id] %>">

	<label for="secret">Secret</label>
	<input type="text" name="secret[title]" id="secret">
	<br>

	<input type="submit">
</form>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<ul>
	<% @users.each do |user| %>
		<li>
			<%= link_to user.username, user_url(user) %>
			<div class="friend-buttons
			 <%= "can-friend" if Friendship.can_friend?(current_user.id, user.id) %>
			 <%= "can-unfriend" if Friendship.can_unfriend?(current_user.id, user.id) %>">

				<button class="friend" data-in="<%= user.id %>">Add Friend</button>
				<% f_id = nil %>
				<% if Friendship.can_unfriend?(current_user.id, user.id) %>
					<% f_id = @friendships.find{ |f| f.in_friend_id == user.id }.id %>
				<% end %>

				<button class="unfriend"
					data-friendship="<%= f_id %>">Remove Friend</button>
			</div>
		</li>
	<% end %>
</ul>

<script>
	$('.friend').on('click', function(event){
		// event.preventDefault();

		$this = $(this);
		var inId = $this.data("in");

		$.ajax({
			url:"/users/" + inId + "/friendships",
			type: "POST",
			success: function(data){
				$this.parent().toggleClass('can-friend can-unfriend');
				$this.siblings('.unfriend').data('friendship', data.id);
			}
		});

		// $this.text('Friending...');
		// $this.off('click');
	});

	$('.unfriend').on('click', function(event){
		// event.preventDefault();

		$this = $(this);
		var friendId = $this.attr("data-friendship");

		$.ajax({
			url:"/friendships/" + friendId,
			type: "DELETE",
			success: function(){
				$this.parent().toggleClass('can-friend can-unfriend');
			}
		});

		// $this.text('Ruining Friendship...');
		// $this.off('click');
	});
</script>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<script type="application/json" id="bootstrapped_tags_json">

	{ "tags": <%= Tag.all.to_json.html_safe %> }

</script>

<script type='text/template' id='tags_template'>
	<select name="tag_ids">
		<%% _(tags).each(function (tag) { %>
			<option value="<%%= tag.id %>"><%%= tag.name %></option>
		<%% }); %>
	</select>
</script>

<h1><%= @user.username %></h1>

<h2>Secrets</h2>
<ul id='user_secrets'>
  <% @user.received_secrets.each do |secret| %>
    <li><%= secret.title %></li>
  <% end %>
</ul>


<%= render "secrets/form" %>

<script>
	var tags = JSON.parse($('#bootstrapped_tags_json').html());
	var templateCode = $("#tags_template").html();
	var templateFn = _.template(templateCode);
	var renderedContent = templateFn(tags);
	$("#secret_submit").before($(renderedContent));

	$('#secret_submit').on('click', function(event) {
		event.preventDefault();
		$("#secret_submit").before($(renderedContent));
	});

	$('.secret').on('submit', function(event){
		event.preventDefault();
		var $this = $(this);
		var formData = $this.serializeJSON();

		$.ajax({
			type: "POST",
			url: "/secrets/",
			data: formData,
			success: function(response){
				console.log(response);
				var secret = $("<li>").text(response.title);
				$('#user_secrets').prepend(secret);
				$('#secret').val('');
			}
		});
	});

</script>